spring:
  datasource:
    url: jdbc:mysql://localhost:3306/demo
    username: user
    password: Admin@1234
  jpa:
    hibernate:
      naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
    properties.hibernate.globally_quoted_identifiers: true
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  rabbitmq:
    host: localhost
    port: 5672
    username: rabbitmq
    password: rabbitmq
    virtual-host: /


spring.servlet.multipart.max-file-size: 2MB
spring.servlet.multipart.max-request-size: 2MB